[package]
name = "codecrafters-redis"
version = "0.1.0"
authors = ["Luis Barroso"]
edition = "2024"

[dependencies]
thiserror = "2.0.12"
tokio = { version = "1.47.1", features = ["full", "test-util"] }